#!/usr/bin/env python3
# encoding: utf-8


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.ap_library(
        name='AP_ShoesAgtech',
        src='AP_ShoesAgtech.cpp',
        dependencies=['AP_HAL', 'AP_Param', 'AP_Common', 'AP_Math',
                      'GCS_MAVLink', 'AP_AHRS', 'RC_Channel', 'SRV_Channel',
                      'AP_RTC'],
    )
